// Code generated by hero.
// source: /Users/kakao/privatework/testspace/golang_test/hero_template/userlist.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func UserList(userList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    `)
	for _, user := range userList {
		buffer.WriteString(`
<ul>
    `)
		buffer.WriteString(`<li>
    `)
		hero.EscapeHTML(user, buffer)
		buffer.WriteString(`
</li>`)
		buffer.WriteString(`
</ul>
`)
	}

	buffer.WriteString(`
</body>
</html>`)

}
